name: CI
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        run: mvn clean install -DskipTests

#      - name: SonarCloud scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-host-url: http://localhost:9000  # URL do seu servidor SonarQube
          sonar-login: ${{ secrets.SONAR_TOKEN }}  # Configure este token como secret nas configurações do repositório
          sonar-project-key: "api-comanda"
          sonar-project-name: "project-comanda"
          sonar-java-binaries: '**/target/**'  # Diretório onde estão os arquivos binários Java
